### ISSUE TITLE
m.points is not a function.

### ISSUE THREAD

**Issue by Dcatfly** [taobaofed/imgcook#1]
version: imgcook@1.6.3, sketch@51.2
description: 有的导出成功，有的导出失败。
![image](https://user-images.githubusercontent.com/18019959/50737475-bc4f6600-1204-11e9-8eb7-f5b28b3a1f92.png)

**Comment by Dcatfly** [comment]
@sccgithub 抱歉，无法提供sketch文件，因为这是我前公司的设计图，随意发给他人不太好。。
目前插件我更新到1.6.5，但是仍然无法导出。。并且点击导出后一直处于运行状态，造成sketch假死。
另外我导出的是整个页面的设计图，不知道是不是由于模块太多了导致的。。

**Comment by Dcatfly** [comment]
@Tinple 我考虑到了这个，但是我觉得即便太多了也不应该抛出这种异常。本质上还是一个bug。

**Comment by sccgithub** [comment]
@Dcatfly sketch插件机制本身性能不佳，我们后续会不断的优化导出性能，目前还是单模块导出体验比较好
