### ISSUE TITLE
请问下应该如何做屏幕适配

### ISSUE THREAD

**Issue by bulolo** [taobaofed/imgcook#12]
我在生成code后，讲代码复制到小程序内，最终显示出来于屏幕大小不对，想请问一下我应该怎么来适配屏幕比例，是我需要在手动的去调整宽高？还是有自动的方式我没了解到？

![image](https://user-images.githubusercontent.com/10026498/52043056-a9b51c00-2579-11e9-850a-ec2f8e067b97.png)

还是说应该在sketch规范好尺寸？

**Comment by Tinple** [comment]
应该是设计稿的设计规范不对，可能你的是1倍的375设计稿，默认我们是使用2倍的750宽设计稿的，微信的单位也是按照750去计算的。

你可以在平台上更改你的设计稿宽度 750 -> 375 ，保存后重新查看样式代码

![image](https://user-images.githubusercontent.com/5363119/52099212-3826ad80-260d-11e9-9bac-3a38cd59ec72.png)

**Comment by thegoldenyou** [comment]
我也遇到了这个问题，的确是设计稿的尺寸问题。

可以在 imgcook 中设置(说明)上传的设计稿的宽高，然后生成出来的 css 尺寸应该就是正常的了。
![image](https://user-images.githubusercontent.com/15965259/117775445-1cd78d80-b26d-11eb-96e6-5b7a5655563a.png)
