### ISSUE TITLE
会支持 adobe xd 吗？

### ISSUE THREAD

**Issue by xiamu14** [taobaofed/imgcook#14]
Adobe XD 还蛮好用的，未来可能考虑支持 吗？

**Comment by sccgithub** [comment]
目前我们主要在做对PS插件的支持，短期内不会支持Adobe XD，长期的话我们会根据用户反馈和持续调研的结果考虑是否支持XD插件

**Comment by zhangxin090** [comment]
同问 Adobe XD插件

**Comment by qq447665722** [comment]
XD是MAC windows双平台通用,建议尽快支持

**Comment by joket1999** [comment]
希望有XD插件，毕竟XD支持Windows和MacOS平台
