### ISSUE TITLE
ps 2019 是还没有支持吗

### ISSUE THREAD

**Issue by chuck-bass** [taobaofed/imgcook#18]
* **pluginVersion**:1.0.1

安装好了ps 的 imgcook插件之后，启动imgcook，没有任何反应；
改了注册表之后仍然如此。
ps版本是 2019

**Comment by jerrytang67** [comment]
我这里用2019 cc可以的

**Comment by Tinple** [comment]
点击插件，如果窗口没出现或者没有反应可能还是证书问题，能否贴图看看注册表里的更改，如果本机上有多个版本的PS,要注意下修改的是不是对应上2019的版本

**Comment by chuck-bass** [comment]
已经解决了，是一些配置没有做
