### ISSUE TITLE
带 rotate 变换的元素转换有问题

### ISSUE THREAD

**Issue by xiehuiqi220** [taobaofed/imgcook#2]
* **pluginVersion**: 1.6.5
* **sketchVersion**: 52.5
* **sketchFile**: [工厂.zip](https://github.com/taobaofed/imgcook/files/2739773/default.zip)

带旋转变换的矩形转换有问题，看下这个例子，原图：

![image](https://user-images.githubusercontent.com/1331211/50884025-b2a44900-1424-11e9-8b18-1424660a1f6a.png)

转换后：

![image](https://user-images.githubusercontent.com/1331211/50884061-c5b71900-1424-11e9-83b7-b81d302a22ea.png)

**Comment by Tinple** [comment]
rotate 问题已收录，如果右上角图层属于静态数据，可暂时对相应图层加个『合并』命名绕过

![](https://gw.alicdn.com/tfs/TB1Zcq9A7voK1RjSZFDXXXY3pXa-1502-544.png)

**Comment by sccgithub** [comment]
已在1.6.7中修复该问题。
