### ISSUE TITLE
imgcook 插件导出数据有问题

### ISSUE THREAD

**Issue by doublenian** [taobaofed/imgcook#3]
* **pluginVersion**: 1.6.5
* **sketchVersion**: 50.2
* **sketchFile**: 内容推荐.sketch

[内容推荐.sketch.zip](https://github.com/taobaofed/imgcook/files/2739860/sketch.zip)

**报错内容 :**
`导出过程出错，请重试
l.style is not a function. (In 'l.style()', 'l.style' is undefined)`

**报错的截图 :**
![image](https://user-images.githubusercontent.com/2343611/50885383-87bbf400-1428-11e9-8a8c-8dc4c55c76cf.png)

**Comment by Tinple** [comment]
我最新的sketch（52.5）打开你的这个文件设计稿本身也会出现样式错乱，建议升级到最新版sketch（目前52.5）再下载demo文件尝试，sketch 软件本身升级会有一些不兼容的问题出现，目前插件只兼容最新版本~ 后续会在文档中做下这部分的说明

**Comment by doublenian** [comment]
> 我最新的sketch（52.5）打开你的这个文件设计稿本身也会出现样式错乱，建议升级到最新版sketch（目前52.5）再下载demo文件尝试，sketch 软件本身升级会有一些不兼容的问题出现，目前插件只兼容最新版本~ 后续会在文档中做下这部分的说明

最新的也会样式错乱，这个是什么问题，我的这个demo 是 imgcook 官网上的例子啊

**Comment by Tinple** [comment]
> > 我最新的sketch（52.5）打开你的这个文件设计稿本身也会出现样式错乱，建议升级到最新版sketch（目前52.5）再下载demo文件尝试，sketch 软件本身升级会有一些不兼容的问题出现，目前插件只兼容最新版本~ 后续会在文档中做下这部分的说明
> 
> 最新的也会样式错乱，这个是什么问题，我的这个demo 是 imgcook 官网上的例子啊

可能是老版本已经对文件结构做了修改，升级到最新版sketch后重新下载官网上的例子打开 demo 看看
