### ISSUE TITLE
支持移动端的适配吗？

### ISSUE THREAD

**Issue by CuveeCui** [taobaofed/imgcook#6]
* **pluginVersion**:
* **sketchVersion**:
* **sketchFile**:

**Comment by Tinple** [comment]
目前 Weex 相关的 DSL 比如 Rax 是有做移动端的适配的，原生H5环境暂时没有，正在考虑这块的适配支持

**Comment by sccgithub** [comment]
目前已经支持vw\vh以及rem两种移动端适配方式
